_pp13.6TeVFD:
    Particle: 'LAMBDAC_TO_PKPI'
    PtMin: [1.]
    PtMax: [2.]
    MassMin: [2.21]
    MassMax: [2.356]
    Rebin: [2]
    Mult: [null]
    MultLatex: ["Minimum Bias"]
__pp13.6TeVFD:
    Particle: 'LAMBDAC_TO_PKPI'
    PtMin: [4.]
    PtMax: [5.]
    MassMin: [2.19]
    MassMax: [2.38]
    Rebin: [2]
    Mult: ["01"]
    MultLatex: ["<d#it{N}_{ch}/d#it{#eta}> = 20.07"]
pp13.6TeVFD:
    Particle: 'LAMBDAC_TO_PKPI'
    PtMin: [8.]
    PtMax: [10.]
    MassMin: [2.1]
    MassMax: [2.456]
    Rebin: [4]
    Mult: [7085]
    MultLatex: ["<d#it{N}_{ch}/d#it{#eta}> = 4.34"]
